# Generated by Django 2.0.1 on 2018-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
