# Generated by Django 2.0.1 on 2018-04-27 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_example_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='name',
        ),
        migrations.AlterField(
            model_name='example',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
