# Generated by Django 2.0.1 on 2018-04-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180427_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
