# Generated by Django 2.0.1 on 2018-06-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180602_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='author',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
